### ISSUE TITLE
[Bug] Channel not defined error

### ISSUE THREAD

**Issue by MrNNP** [DrMoraschi/AFKBot#14]
Getting a channel not found error

 - OS Windows:
 - Node version 12.16.0:
 - Minecraft version 1.14.4:

Expected bot to start up and run. 

Only changes are to config, set ip, bot token, and channel id

Log: 
 <DISCORD> Token found
 <WORLD> Online players: AFKBot
 <WORLD> Current time: 7437
 <STATUS> Spawned at x: -127 y: 79 z: -217
C:\Users\aquas\Documents\coding stuff ig\github stuff\minecraft-afk-discord-bot\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'send' of undefined
    at Bot.<anonymous> (C:\Users\aquas\Documents\coding stuff ig\github stuff\minecraft-afk-discord-bot\index.js:105:29)
    at Object.onceWrapper (events.js:427:28)
    at Bot.emit (events.js:333:22)
    at Client.<anonymous> (C:\Users\aquas\Documents\coding stuff ig\github stuff\minecraft-afk-discord-bot\node_modules\mineflayer\lib\plugins\health.js:21:9)
    at Client.emit (events.js:333:22)
    at FullPacketParser.<anonymous> (C:\Users\aquas\Documents\coding stuff ig\github stuff\minecraft-afk-discord-bot\node_modules\minecraft-protocol\src\client.js:89:12)
    at FullPacketParser.emit (events.js:321:20)
    at addChunk (C:\Users\aquas\Documents\coding stuff ig\github stuff\minecraft-afk-discord-bot\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\aquas\Documents\coding stuff ig\github stuff\minecraft-afk-discord-bot\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\aquas\Documents\coding stuff ig\github stuff\minecraft-afk-discord-bot\node_modules\readable-stream\lib\_stream_readable.js:241:10)

**Comment by DrMoraschi** [comment]
Did you write the correct channel id in the channelID in the configmjson?

**Comment by MrNNP** [comment]
Yes I did, double checked and its the right one, the bot also has perms to access and send/read messages in the channel

**Comment by DrMoraschi** [comment]
Well, that error means it couldn't find a channel with that ID in any of the servers. Maybe try to set the role of the bot as an administrator?

**Comment by MrNNP** [comment]
Ok I went through and enabled every permission include the administrator perm, and it worked.

**Comment by DrMoraschi** [comment]
Oh xD
