### ISSUE TITLE
[BUG] DiscordAPIError: Cannot send an empty message

### ISSUE THREAD

**Issue by ZunDubCore** [DrMoraschi/AFKBot#19]
**Describe the bug**
After starting the bot via discord, I must execute `/login pass` command to enter the minecraft server. But after writing `/login pass` , I am getting the following error:

```
<src/Logging.js> started
<src/Logging.js> function checkLatestLog
<index.js> starting up
<src/Discord.js> creating bot
<src/Discord.js> retrieving channel
<src/Discord.js> starting ./DiscordFunctions
<src/Pathfind.js> load pathfind
<src/Fishing.js> started
<src/Inventory.js> Started
<DISCORD> Logged in: [TEST] AFK Minecraft Bot#2172
<src/DiscordFunctions.js> logged in
<src/DiscordFunctions.js> sent command list
<src/Bot.js> starting bot
<src/Windows.js> started
<src/EventFunctions.js> load functions
<src/Eat.js> load autoEat
<src/Eat.js> disable autoEat
<src/Viewer.js> function startviewer
<src/BotFunctions.js> load resource pack
<src/BotFunctions.js> load events
<src/BotFunctions.js> load functions
<src/BotFunctions.js> load discord event
Prismarine viewer web server running on *:3000
<src/Eat.js> enable autoEat
<src/Eat.js> disable autoEat
<CHAT> Use /login <password>.
<CHAT> You have 59 seconds to login.
<CHAT> You have 58 seconds to login.
<CHAT> You have 57 seconds to login.
<CHAT> Login sucessful.
<CHAT>
<src/Eat.js> enable autoEat
[...]\AFKBot\node_modules\discord.js\src\rest\RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute ([...]\AFKBot\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async RequestHandler.push ([...]\AFKBot\node_modules\discord.js\src\rest\RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/806894505592094730/messages',
  code: 50006,
  httpStatus: 400
}
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node version: v15.8.0
 - Minecraft version: 1.16.5

**Comment by DrMoraschi** [comment]
Yes, that means the server is sending an empty message, I will fix it. If you want a quick fix, try disabling the option to send the chat to discord

**Comment by ZunDubCore** [comment]
@DrMoraschi Okay, thank you. If you need any help feel free to contact me.

**Comment by ZunDubCore** [comment]
@DrMoraschi Would you mind implementing a login feature? Therefore I wouldn't have to type `/login pass` every time I want to login into some servers.

**Comment by DrMoraschi** [comment]
I'll try, I'm busy these days, but I could look into it

**Comment by ZunDubCore** [comment]
@DrMoraschi Thanks for your effort.

**Comment by DrMoraschi** [comment]
Release updated with a fix for the empty message error. You'll have to wait a week or something for the login feature tho.
