### ISSUE TITLE
[BUG] GoalChanged: The goal was changed before it could be completed!

### ISSUE THREAD

**Issue by ZunDubCore** [DrMoraschi/AFKBot#21]
**Describe the bug**
The bot crashes when middle click on `prismarine-viewer` to change destination while already going to one.

```
[...]\AFKBot\node_modules\mineflayer-pathfinder\lib\goto.js:2
  const err = new Error(message)
              ^

GoalChanged: The goal was changed before it could be completed!
    at error ([...]\AFKBot\node_modules\mineflayer-pathfinder\lib\goto.js:2:15)
    at EventEmitter.goalChangedListener ([...]\AFKBot\node_modules\mineflayer-pathfinder\lib\goto.js:32:17)
    at EventEmitter.emit (node:events:378:20)
    at Object.bot.pathfinder.setGoal ([...]\AFKBot\node_modules\mineflayer-pathfinder\index.js:101:9)
    at PVP.stop ([...]\AFKBot\node_modules\mineflayer-pvp\lib\PVP.js:74:20)
    at gotoCoord ([...]\AFKBot\src\Pathfind.js:59:17)
    at EventEmitter.<anonymous> ([...]\AFKBot\src\Viewer.js:34:13)
    at EventEmitter.emit (node:events:378:20)
    at WorldView.<anonymous> ([...]\AFKBot\node_modules\prismarine-viewer\lib\mineflayer.js:49:18)
    at WorldView.emit (node:events:378:20)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node version: v15.8.0
 - Minecraft version: 1.16.5

**Comment by DrMoraschi** [comment]
Does this happen when you 1. Do a goto command and then click a position in the viewer or 2. Click a position in the viewer and then click another position?

**Comment by ZunDubCore** [comment]
@DrMoraschi 2. When I click one position and then another immediately.

**Comment by DrMoraschi** [comment]
Allright

**Comment by DrMoraschi** [comment]
Fixed on next release
