### ISSUE TITLE
I got an error while trying to run index.js

### ISSUE THREAD

**Issue by Momotin** [DrMoraschi/AFKBot#27]
**Describe the bug**
got an error while trying to run index.js

**Desktop (please complete the following information):**
 - OS [e.g. Windows]:Windows 10
 - Node version [e.g. 12.18.3]:V14.16.0
 - Minecraft version [e.g. 1.16.1]:1.16.5

**Expected behavior**
i expected it to run.

**Screenshots**
![image](https://user-images.githubusercontent.com/80270576/110339804-3cfe8c80-8031-11eb-9d25-18f1a1f0cf01.png)

**Additional context**
im new to java/js/json so i dont know how to fix the problem, if someone could help it would be nice.

**Comment by DrMoraschi** [comment]
Ok, this error means that JSON couldn't parse it correctly, I think you didn't put the token of the Discord Bot inside quotation marks, you have to put it like this: "token".

**Comment by Momotin** [comment]
I got another error.

internal/modules/cjs/loader.js:1109
    throw err;
    ^

 in JSON at position 447lam\Desktop\afk\config.json: Unexpected token
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\salam\Desktop\afk\index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

C:\Users\salam\Desktop\afk>

**Comment by DrMoraschi** [comment]
Ok, quotation marks can't be removed, you only need to edit the inside of the quotation marks (" "). For example, in this case, if you want to fill in the "channel-id", the ID should be like this: "channel-id": "xxxxxxxxxxxxxxxxxx".

**Comment by Momotin** [comment]
Everything is inside the quotation marks i dont know whats wrong, i checked multiple times.

**Comment by DrMoraschi** [comment]
Could you send your config.json (dremoving some fields that are private)? Maybe it's better if you DM me in Discord, you can find the invite button at the top of the README
