### ISSUE TITLE
[BUG] Error: Version 1.7.10 is not supported.

### ISSUE THREAD

**Issue by nikidziuba** [DrMoraschi/AFKBot#30]
**Describe the bug**
When I try to run it on 1.16.5 server it says that 1.7.10 is not supported and crashes

**Desktop (please complete the following information):**
 - OS [e.g. Windows]: Windows 10 (I think it's a pro versions)
 - Node version [e.g. 12.18.3]: can't remember right now, will update when I get on my pc tommorow
 - Minecraft version [e.g. 1.16.1]: 1.16.5

**Expected behavior**
I expected a bot to join my server

**Screenshots**
Here's a log:
```
/app/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

Error: Version 1.7.10 is not supported.
    at Client.next (/app/node_modules/mineflayer/index.js:110:13)
    at Object.onceWrapper (node:events:475:28)
    at Client.emit (node:events:381:22)
    at /app/node_modules/minecraft-protocol/src/client/autoVersion.js:53:12
    at Client.<anonymous> (/app/node_modules/minecraft-protocol/src/ping.js:39:7)
    at Object.onceWrapper (node:events:476:26)
    at Client.emit (node:events:369:20)
    at FullPacketParser.<anonymous> (/app/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (node:events:369:20)
    at addChunk (/app/node_modules/readable-stream/lib/_stream_readable.js:298:12)
```

**Additional context**
I haven't updated node in few months so it can be a problem

**Comment by DrMoraschi** [comment]
Is your server 1.7.10?
1.7.10 is not supported, but if it's 1.16.5 as you say, it might be a bug. I'll look into it.

**Comment by DrMoraschi** [comment]
Do you still have this problem?
mineflayer now only supports node >= v14 so it might be a problem too as you said
Could you join the Discord Server and send the IP of the server there so that I can test it?

**Comment by nikidziuba** [comment]
I have reinstalled node just now and it works, thanks for your help
